{{- if .Values.rabbitmq.autocreate }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.redis.hostname }}
  name: {{ .Values.redis.hostname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.hostname }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.hostname }}
    spec:
      containers:
        - image: redis
          imagePullPolicy: IfNotPresent
          name: {{ .Values.redis.hostname }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.redis.hostname }}
  name: {{ .Values.redis.hostname }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: {{ .Values.redis.hostname }}
  type: {{ .Values.redis.type }}
{{- end }}