{{- range $index, $value := .Values.secret }}
{{- if $value.dockerconfigjson }}
apiVersion: v1
data:
  .dockerconfigjson: {{ $value.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ $value.name }}
  namespace: {{ $.Values.namespace }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}
{{- end }}