{{- if .Values.rabbitmq.autocreate }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.hostname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.hostname }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.hostname }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.hostname }}
        image: rabbitmq:3.11.5-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15672
          name: rabbit15672
          protocol: TCP
        - containerPort: 5672 
          name: rabbit5672 
          protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.username }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.password }}
---
apiVersion: v1  
kind: Service  
metadata:  
 name: {{ .Values.rabbitmq.hostname }}
 namespace: {{ .Values.namespace }}
spec:  
 type: {{ .Values.rabbitmq.type }}
 ports:  
 - name: rabbit15672
   port: 15672  
   protocol: TCP  
   targetPort: 15672  
 - name: rabbit5672   
   port: 5672   
   protocol: TCP   
   targetPort: 5672  
 selector:
   app: {{ .Values.rabbitmq.hostname }}
{{- end }}