kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.swprintergatewayservice.serviceAccountName }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.swprintergatewayservice.serviceAccountName }}-role-bind
  namespace: swprinter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ .Values.swprintergatewayservice.serviceAccountName }}
    namespace: {{ .Values.namespace }}