apiVersion: v1
kind: ConfigMap
metadata:
  name: apiconfig
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |
   {
    "RedisCache": { 
      {{- if .Values.redis.autocreate }}
      "ConnectionString": "{{ .Values.redis.hostname }}.{{ .Values.namespace }},allowAdmin=true,connectTimeout=60000,syncTimeout=60000",
      {{- end }}
      "Sentinel": []
    },
    "DownloadUrl": {{ .Values.externalapi.getway }},
    "Identity_Config": {
      "Authority": {{ .Values.externalapi.authority }},
      "Audience": "ApiOne",
      "IsHttps": false,
      "ValidateIssuer": true,
      "ValidateAudience": false
    },
    "BomUrl": "http://{{ .Values.swprinterbomservice.fullname }}.{{ .Values.namespace }}/",
    "AutoUrl": "http://{{ .Values.swprinterautoservice.fullname }}.{{ .Values.namespace }}/",
    "ERPCoreConfig": {
      "LoopCronTime": "*/20 * * * *",
      "ClearSqlLoopCronTime": "0 0/5 * * * ?",
      "IsServer": "True",
      "IsLaunch": "True",
      "ERPHandlerCount": "500"
    },
    "ConfigJsonPath": "Config/",
    "AllowedHosts": "*",
    "ConnectionStrings": {
      "CapConnection": "Data Source={{ .Values.db.swpsqlserver.host }};Initial Catalog={{ .Values.swprinterapiservice.database.cap }};User ID={{ .Values.db.swpsqlserver.user }};Password={{ .Values.db.swpsqlserver.pwd }};Pooling=False",
      "HangfireConnection": "Data Source={{ .Values.db.swpsqlserver.host }};Initial Catalog={{ .Values.swprinterapiservice.database.hangfire }};User ID={{ .Values.db.swpsqlserver.user }};Password={{ .Values.db.swpsqlserver.pwd }};Pooling=False",
      "SqlServiceDBConnection": "Server={{ .Values.db.swpsqlserver.host }};database={{ .Values.swprinterapiservice.database.api }};uid={{ .Values.db.swpsqlserver.user }};pwd={{ .Values.db.swpsqlserver.pwd }}",
      "DBWorksConnection": "Integrated Security = False;Data Source={{ .Values.db.dbwork.host }};Initial Catalog={{ .Values.swprinterapiservice.database.dbworks }};User ID={{ .Values.db.dbwork.user }};Password={{ .Values.db.dbwork.pwd }};MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=True"
    },
    "RabbitMQ": {
      "HostName": "{{ .Values.rabbitmq.hostname }}.{{ .Values.namespace }}.svc.cluster.local",
      "UserName": "{{ .Values.rabbitmq.username }}",
      "Password": "{{ .Values.rabbitmq.password }}",
      "VirtualHost": "/",
      "ExchangeName": "Inglass_Convert_queue"
    },
    "Consul": {
      "ConsulUri": "http://consul-server.consul.svc.cluster.local:8500/",
      "Datacenter": "dc1",
      "ip": "swapi",
      "port": 5000,
      "ID": "swapi",
      "Name": "SW_Printer_API_Service",
      "weight": 1
    },
    "https_port": 443,
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information",
        "DotNetCore.CAP.RabbitMQ.RabbitMQTransport": "Error",
        "DotNetCore.CAP.Internal.SubscribeDispatcher": "Error"
      }
    },
    "CapConsulConfig": {
      "UseConsul": false,
      "ConsulServerName": "consul-server.consul.svc.cluster.local",
      "ConsulServerPort": 8500
    },
    "EmailTemplate": {
      "SubjectTemplate": "Print job %ProjectCode%",
      "BodyTemplate": "%TestText% Dear %DesignerName%,<br/>please check following tasks for project %ProjectCode%:<br/><br/>Job Delivery Date: %DeliveryDate%<br/>Lock BOM: %LockBOMs%<br/><br/>Plates files: <br/>%Platesfiles%<br/><br/><span style='color: red;'>If you are receiving this message, please check and release drawing files on server.</span><br/><br/><br/>Regards,<br/>Data Transmission Dept."
    },
    "AutoCoreBreakConfig": {
      "ConvertCronTime": "0 0 12 ? * WED",
      "UploadCronTime": "0 0 13 ? * WED",
      "AutoArea": "1000"
    },
    "UserDefaultSet": {
      "Password": "123456"
    },
    "NowApolloNameSpace": "{{ .Values.apollo.namespaces.api }}",
    "Apollo": {
      "AppId": "{{ .Values.apollo.AppId }}",
      "Env": "{{ .Values.apollo.Env }}",
      "MetaServer": "{{ .Values.apollo.MetaServer }}",
      "ConfigServer": [ "{{ .Values.apollo.ConfigServer }}" ]
    }
   }