apiVersion: v1
kind: ConfigMap
metadata:
  name: autoconfig
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |
   {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "NowApolloNameSpace": "{{ .Values.apollo.namespaces.auto }}",
    "UploadSharepoint": {
      "SharePointMaxFiles": 10000,
      "SPSiteUrl": "{{ .Values.back.sharepoint.url }}",
      "SPUsername": "{{ .Values.back.sharepoint.username }}",
      "SPPassword": "{{ .Values.back.sharepoint.pwd }}",
      "AADAppId": "{{ .Values.back.sharepoint.appid }}",
      "AADAppSecret": "{{ .Values.back.sharepoint.appsecret }}"
    },
    "ConnectionStrings": {
      "SqlServiceDBConnection": "Server={{ .Values.db.swpsqlserver.host }};database={{ .Values.swprinterautoservice.database.api }};uid={{ .Values.db.swpsqlserver.user }};pwd={{ .Values.db.swpsqlserver.pwd }};MultipleActiveResultSets=true;Connect Timeout=100;"
    },
    "AutoBaseCache": {
      "ConnectionString": "{{ .Values.redis.hostname }}.{{ .Values.namespace }},allowAdmin=true,connectTimeout=60000,syncTimeout=60000",
      "Sentinel": []
    },
    "BomUrl": "https://{{ .Values.swprinterbomservice.fullname }}.{{ .Values.namespace }}/",
    "AutoUrl": "http://{{ .Values.swprinterautoservice.fullname }}.{{ .Values.namespace }}/",
    "DaprCache": {
      "storeName": "{{ .Values.dapr.statestore }}",
      "lockstoreName": "{{ .Values.dapr.lockstore }}"
    },
    "DaprConfig": {
      "daprLockStore": "{{ .Values.dapr.lockstore }}",
      "daprStateStore": "{{ .Values.dapr.statestore }}",
      "daprActorId": ""
    },
    "Apollo": {
      "AppId": "{{ .Values.apollo.AppId }}",
      "Env": "{{ .Values.apollo.Env }}",
      "MetaServer": "{{ .Values.apollo.MetaServer }}",
      "ConfigServer": [ "{{ .Values.apollo.ConfigServer }}" ]
    },
    "AllowedHosts": "*"
   }
