apiVersion: v1
kind: ConfigMap
metadata:
  name: identityconfig
  namespace: {{ .Values.namespace }}
data:
  appsettings.json: |
   {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "ConnectionStrings": {
      "IdentityServerDbConnection": "Server={{ .Values.db.swpsqlserver.host }};database={{ .Values.swprinteridentityservice.database.identity }};uid={{ .Values.db.swpsqlserver.user }};pwd={{ .Values.db.swpsqlserver.pwd }}"
    },
    "ThreeDataConfig": {
      "ConnString": "Server={{ .Values.db.swpsqlserver.host }};database={{ .Values.swprinteridentityservice.database.api }};uid={{ .Values.db.swpsqlserver.user }};pwd={{ .Values.db.swpsqlserver.pwd }}",
      "DefaultRoleID": "8AEB423E-F36B-1410-8E0D-002782F598A9"
    },
    "Apollo": {
      "AppId": "{{ .Values.apollo.AppId }}",
      "Env": "{{ .Values.apollo.Env }}",
      "MetaServer": "{{ .Values.apollo.MetaServer }}",
      "ConfigServer": [ "{{ .Values.apollo.ConfigServer }}" ]
    },
    "AllowedHosts": "*",
    "IdentityServerConfig": {
      "apiResources": [
        {
          "name": "ConvertAPI",
          "needUserClaim": [ "power", "role", "userid", "area" ]
        }
      ],
      "apiurlarrary": [
        "{{ .Values.externalapi.getway }}","http://{{ .Values.swprinterapiservice.fullname }}.{{ .Values.namespace }}/"
      ],
      "jsClient": {
        "RedirectUris": [
          "https://{{ .Values.ingress.host }}/Home/SignIn",
          "https://{{ .Values.ingress.host }}/devextreme-vue-template/#/home",
          "https://{{ .Values.ingress.host }}/home",
          "https://{{ .Values.ingress.host }}/callback.html",
          "https://{{ .Values.ingress.host }}/silent-renew.html"
        ],
        "PostLogoutRedirectUris": [ 
            "http://{{ .Values.ingress.host }}/Home",
            "http://{{ .Values.ingress.host }}/convert-list",
            "https://login.microsoftonline.com/common/oauth2/v2.0/logout",
            "https://{{ .Values.ingress.host }}/Home",
            "https://{{ .Values.ingress.host }}/convert-list"
            ],
        "AllowedCorsOrigins": [ "http://{{ .Values.ingress.host }}","https://{{ .Values.ingress.host }}"]
      }
    },
    "NowApolloNameSpace": "{{ .Values.apollo.namespaces.identity }}",
    "IsEmptyLinkTo": "https://{{ .Values.ingress.host }}/convert-list",
    "IsEmptyLinkToPublicPage": "https://{{ .Values.ingress.host }}/convertinfov1",
    "MicrosoftAccount": {
      "ClientId": "{{ .Values.MicrosoftAccount.ClientId }}",
      "ClientSecret": "{{ .Values.MicrosoftAccount.ClientSecret }}",
      "TenantId": "organizations",
      "CallbackPath": "/signin-microsoft",
      "SignedOutCallbackPath": "https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri={Redirect}"
    }
   }